use std::sync::LazyLock;
use std::collections::HashMap;

pub static ORDR_SKINS: LazyLock<HashMap<&str, &str>> = LazyLock::new(|| {
    HashMap::from([
        ("-atmosphere-", "- a t m o s p h e r e -"),
        ("105_degrees_c_chocolate", "105°C Chocolate"),
        ("a21_red_azurlane_edit", "A21 red azurlane edit"),
        ("adamqs_2017_10_30", "Adamqs 2017-10-30"),
        ("adeus", "Adeus"),
        ("aesthetic_1_3_1", "Aesthetic 1.3.1"),
        ("aesthetic_1_3_2", "Aesthetic 1.3.2"),
        ("aesthetic_vazurlane1_0", "aesthetic vAzurlane 1.0"),
        ("aetrna_aug_2020_fir3ba7", "Aetrna aug. 2020 fir3ba7"),
        ("aetrnaaberratefujiwara_v3", "aetrnaaberatteFujiwara v3"),
        ("aetrnaaberratefujiwara_v2", "aetrnaaberrateFujiwara v2"),
        ("affliction_lite_hrk", "Affliction (HRK)"),
        ("ai_hayasaka_v3_0", "Ai Hayasaka v3.0"),
        ("aimnotfound_404_2018_10_20_ez", "AimNotFound 404 (2018-10-20) EZ"),
        ("aitsuki_nakuru", "Aitsuki Nakuru"),
        ("akai_haato_v1_0", "Akai Haato v1.0"),
        ("akcel_2017_08_10", "Akcel 2017-08-10"),
        ("alcolle_2_laffey", "ALColle 2 - Laffey"),
        ("alice_margatroid", "Alice Margatroid"),
        ("alice_zuberg", "Alice Zuberg"),
        ("amaestric_1_1", "Amaestric 1.1"),
        ("amarillo_updatedcirclesandcursor", "Amarillo"),
        ("amasetic_3", "Amasetic 3"),
        ("amelia_watson", "Amelia Watson"),
        ("andres_mind_lite_sk", "Andre's Mind"),
        ("andromeda_v2_0", "Andromeda v2.0"),
        ("angelmegumin_remake", "AngeLMegumin Remake"),
        ("angelsim_2", "Angelsim #2"),
        ("aoalien_fix", "AoAlien"),
        ("apostol_pirasto", "Apostol"),
        ("aprixia_aizawa", "Aprixia Aizawa"),
        ("aristia_edit_trail", "Aristia (edit +trail)"),
        ("aristia_jacky_lol_edit", "Aristia Jacky lol Edit"),
        ("arknights_chen_v2_1_nonweeb_ver", "Arknights Chen v2.1 non-weeb ver."),
        ("arnold24x24_skin", "Arnold24x24 skin"),
        ("as_holo", "AS Holo"),
        ("as_zero_two_redo", "AS Zero Two Redo"),
        ("ashuramaru", "Ashuramaru"),
        ("aurora_skin_mix", "aurora. Skin Mix"),
        ("ayunda_risu", "Ayunda Risu"),
        ("azer-ite", "azer -ite"),
        ("Azer2018", "Azer 2018"),
        ("azer8dusk", "Azer 2018-06-03 azer8dusk"),
        ("azer8midnightedit", "azer8 midnight edit"),
        ("azerite_1_2", "Azerite 1.2"),
        ("azr8boop", "azr8boop"),
        ("azur_lane_laffey", "Azur Lane - Laffey"),
        ("azure_snowfall", "Azure Snowfall"),
        ("badeu_2018_08_07", "Badeu (2018-08-07)"),
        ("bakanyakanyaikakanyai", "bakanyakanyaikakanyai"),
        ("bananahira", "Bananahira"),
        ("bikkoism_alpha", "Bikkoism Alpha"),
        ("biondesu_ultimate", "Biondesu Ultimate"),
        ("bird_sprite", "Bird sprite"),
        ("black_and_white_white_cursor", "Black and White (white cursor)"),
        ("codename_bloo", "Bloo (codename)"),
        ("bloo_v1_1", "Bloo v1.1"),
        ("bloomoon", "BlooMoon"),
        ("bloomoon_new_lite", "BlooMoon New"),
        ("blooxoo", "BlooXoo"),
        ("bluchoco_v2", "BluChoco v2"),
        ("blueberry_v1_7_0", "Blueberry v1.7.0"),
        ("blueline_ui_v1", "BlueLine UI v1"),
        ("boop", "boop"),
        ("boop_2_0_paraqeet", "Boop 2.0 (Paraqeet)"),
        ("bubblegum", "BubbleGum"),
        ("bubbleskin19_10_25", "BubbleSkin (2019-10-25)"),
        ("bubbleskin20_10_09", "BubbleSkin 20-10-09"),
        ("butterflynino_lite", "ButterflyNino"),
        ("byonick_1_1", "Byonick 1.1"),
        ("calliope_m", "Calliope M"),
        ("cent_hr", "Cent HR"),
        ("chino_kafuu_v7", "Chino Kafuu v7"),
        ("chitanda", "Chitanda"),
        ("chitanda_sz", "Chitanda (SZ)"),
        ("choco_boi_blue", "Choco boi (Seoul x Bacon boi - blue)"),
        ("chocola_vanilla_nekopara", "Chocola & Vanilla - NEKOPARA"),
        ("chocomint1_skin_blend_2_2", "chocomint1 + Skin Blend 2.2"),
        ("chocomint1_skin_blend_3_0", "chocomint1 + Skin Blend 3.0"),
        ("chtholly", "Chtholly"),
        ("cirno_v1_1", "Cirno v1.1"),
        ("cirnoo", "Cirnoo"),
        ("clear_black", "Clear Black"),
        ("clear_skin_ultra_4_0_clean", "Clear Skin Ultra 4.0 Clean"),
        ("clinawi_tenshi_skin_touhou", "Clinawi (Tenshi Skin Touhou)"),
        ("coastal_iridescence", "Coastal Iridescence"),
        ("cocoa_hoto_a7_no_anim", "Cocoa Hoto"),
        ("coffene_minimal", "Coffene - Minimal"),
        ("colorbog", "colorbog"),
        ("comfort", "Comfort"),
        ("concentrated_asacoco_plug_edition", "Concentrated Asacoco Plug Edition"),
        ("confounded", "Confounded"),
        ("cozy_skin", "Cozy Skin"),
        ("crybloo_lite", "CryBloo"),
        ("default", "Danser default skin (Redd glass)"),
        ("dark_saturn_mathi", "Dark Saturn (Mathi)"),
        ("ddd_x13", "ddd+x13"),
        ("dereban_oka", "Dereban Miku"),
        ("devilish_sky_ayame", "Devilish Sky - Nakiri Ayame"),
        ("dgskin_3_1", "DGskin 3.1"),
        ("distant_lite", "Distant"),
        ("doki_doki_circles_club", "Doki Doki Circles Club"),
        ("dumborino_aquakinn_v2", "Dumborino Aquakinn v2"),
        ("dusktale_galactic", "Dusktale Galactic"),
        ("dusktale_v4", "DuskTale v4"),
        ("E.CSr20200326", "E.CS r20200326"),
        ("echidna_v1_1", "Echidna v1.1"),
        ("elaina_ak", "Elaina (AK)"),
        ("elite_beat_osu_hd", "Elite Beat osu! HD 1.0"),
        ("emilia", "Emilia"),
        ("emilia_re_zero", "Emilia (Re:Zero)"),
        ("satella_x_emilia_public_v1_0", "Emilia x Satella 1.0"),
        ("eoii", "eoii"),
        ("eternumonochromia_lite", "EternuMonochromia"),
        ("EZPro", "EZPro"),
        ("farewell_rushia_nomod", "Farewell Rushia (NM)"),
        ("fcuk_edit_2021", "fcuk edit 2021"),
        ("FeriOP2018-06-13", "FeriOP 2018-06-13"),
        ("ferri_chan", "Ferri-chan"),
        ("fierymod_v8_akolibed", "Fierymod v8 Akolibed"),
        ("fierymod_v8_realest_ver_two", "Fieryrage v8 realest ver.2"),
        ("flatoshabe", "FlatoShabe"),
        ("FlyingTunaSelyu2.2", "FlyingTuna 2018-02-15 Selyu v2.2"),
        ("focusneo_candypink", "FocusNeo (CandyPink)"),
        ("fonderman_dt_jumpy", "Fonderman (DT) Jumpy"),
        ("freddie_fami_aireuvv", "freddie fami aireuvv"),
        ("FreedomDiveBTMC", "FREEDOM DiVE (BTMC)"),
        ("funorange_2017_08_10", "FunOrange (2017-08-10)"),
        ("futuristic_blue", "Futuristic Blue"),
        ("g_r_i_s_project", "G R I S Project"),
        ("gabrielsquad_0_1ver", "GabrielSquad 0.1"),
        ("galactic_magic_fy", "Galactic Magic"),
        ("galaxy_noel_viii", "Galaxy Noel VIII"),
        ("gasha_v1_3_dark_blue_normal_hc", "Gasha v1.3 dark blue"),
        ("gawr_gura", "Gawr Gura"),
        ("gawr_gura_twix", "Gawr Gura Twix"),
        ("gawrgura_v2", "GawrGura v2"),
        ("geko_v3", "Geko v3"),
        ("gn_2017_08_10", "GN (2017-08-10)"),
        ("gradient_spam_twilight", "Gradient Spam Twilight"),
        ("grayfump", "GrayFump"),
        ("hachiroku", "Hachiroku"),
        ("haga_remake", "haga1115 remake"),
        ("haimhalo", "haimhalo"),
        ("happy_memories_yuru_camp_v1_0_sd", "Happy Memories - Yuru Camp v1.0"),
        ("hatsune_miku_nm1", "Hatsune Miku (NM)"),
        ("hatsune_miku_nm2", "Hatsune Miku (NM2)"),
        ("hatsunemiku_v1_0", "Hatsune Miku v1.0"),
        ("haxwellskin_v1_1", "HaxwellSkin v1.1"),
        ("tree_rack", "he rack (Rektygon edit)"),
        ("heckin", "heckin"),
        ("himemori_luna_lite", "Himemori Luna"),
        ("hisakawa_nagi_narukiko", "Hisakawa Nagi"),
        ("hiten", "Hiten Chitanda"),
        ("hms_cheshire_b20200904", "HMS Cheshire b20200904"),
        ("hoshimachi_suisei", "Hoshimachi Suisei"),
        ("hoshimachi_suisei_n2_v2_lite", "Hoshimachi Suisei n2 v2"),
        ("hoshino_bluearchive", "Hoshino - BlueArchive"),
        ("houshou_marine_v2", "Houshou Marine v2"),
        ("hu_tao", "Hu Tao"),
        ("hu_tao_no_name_1_0", "Hu Tao no-name 1.0"),
        ("hugofrosty_1.1_fy", "HugoFrosty 1.1 [FY]"),
        ("hurrikate_astolfo_v1_1", "Hurrikate Astolfo v1.1"),
        ("hvick225_kantoku", "hvick225 & Kantoku"),
        ("hyperpigeon_dd", "HyperPigeon DD"),
        ("idke_1_1", "idke 1.1"),
        ("idke_1_2_without_sliderendcircle", "idke 1.2 without sliderendcircle"),
        ("ijn_yamashiro_v2", "IJN Yamashiro v2"),
        ("inabakumori_v1", "Inabakumori v1"),
        ("incandescent_nebulae", "Incandescent Nebulae"),
        ("incandescent_nebulae_ekoro_edit", "Incandescent Nebulae (Ekoro edit)"),
        ("indecent_tranquility", "Indecent Tranquility"),
        ("Informous2018-11-01", "Informous 2018-11-01"),
        ("inugami_korone", "Inugami Korone"),
        ("inugami_korone_nm", "Inugami Korone (NM)"),
        ("inui_toko", "Inui Toko"),
        ("irdios_frankenstein", "irdios frankenstein"),
        ("irdios_mix_v2", "irdios' mix v2"),
        ("Jace-6.25", "Jace 6.25"),
        ("jimmy_rustler_10_08_17", "Jimmy Rustler 2017-10-08"),
        ("jinxiietsun_satania_v2_1", "JinxiieTsun Satania v2.1"),
        ("joie_s_seoul_v9_x_owotuna_whale_digitalhypno", "Joie's Seoul v9 x owoTuna + whale (DigitalHypno)"),
        ("jonys_minimal", "Jony's Minimal"),
        ("joosts_sakura_burst_1_0", "Joost's Sakura Burst 1.0"),
        ("kaguya-sama_v7-HDDT", "Kaguya-sama v7 HDDT No FP"),
        ("kamui_willy_edit_momo_remix", "Kamui Willy edit (momo remix)"),
        ("kano_2018_experimental_2_2", "Kano 2018 (Experimental 2.2)"),
        ("keqing_daremo", "Keqing"),
        ("khz_oka", "khz (Oka)"),
        ("kirino_kasumu_newnamm", "Kirino Kasumu"),
        ("kitagawa_marin_v1_0_nm", "Kitagawa Marin v1.0 (NM)"),
        ("kizuna_akari", "Kizuna Akari"),
        ("klee_smz", "Klee (SMZ)"),
        ("knello_valve", "Knello Valve"),
        ("kochiya", "Kochiya"),
        ("koishi_nm", "Koishi (NM)"),
        ("kokkoro", "Kokkoro"),
        ("konoha_cup", "Konoha Cup"),
        ("konpaku_youmu_v1_1", "Konpaku Youmu v1.1"),
        ("kr_silence", "Kr · Silence"),
        ("kronii_no_jikan", "Kronii no Jikan"),
        ("kuro_zrushia", "Kuro-ZRushia"),
        ("kurumi_tokisaki", "Kurumi Tokisaki"),
        ("kurumi", "Kurumi Tokisaki"),
        ("kyaru", "Kyaru"),
        ("laplus_darkness_btmc_freedom_dive_edit", "Laplus Darkness BTMC FD edit"),
        ("lifeline_v2_dt", "Lifeline v2 (DT)"),
        ("lifeline_v3_dt", "Lifeline v3 (DT)"),
        ("lifeline_v3_pirasto_s_nm", "Lifeline v3 (Pirasto's NM)"),
        ("loki_s_ultimatum_v5_fix", "Loki's Ultimatum V5"),
        ("louisd_meltryllis_nm", "LouisD & Meltryllis (NM)"),
        ("luckdotexe", "LuckDOTexe"),
        ("lunasakurakouji", "LunaSakurakouji"),
        ("m_w", "M - W"),
        ("mafuyu_kirisu_senseikirisu", "Mafuyu Kirisu"),
        ("marine_summer", "Marine Summer"),
        ("aya_1_3a", "Maruyama Aya 1.3a"),
        ("mastasz_but_refreshed_chuj", "Mastasz but refreshed chuj"),
        ("masterio-1", "MasterIO's skin v1"),
        ("mat_chikito", "Mat Chikito"),
        ("Mathi1.0", "Mathi 1.0"),
        ("mathi_ensalada_v1_5_blue_cursor", "Mathi ensalada v1.5 (blue cursor)"),
        ("flyingtuna_2018_06_23_mathituna", "MathiTuna (2018-06-23)"),
        ("mc_noel_vi_komori_lite", "MC Noel VI"),
        ("megamix", "megamix"),
        ("mercy_in_osu", "Mercy in osu"),
        ("metanoia", "Metanoia"),
        ("midnight_phantasmagoria", "Midnight Phantasmagoria"),
        ("miku_sleepingd", "Miku 16:9"),
        ("milkteaism_lunar_v1_1_oddity", "Milkteaism Lunar v1.1"),
        ("milkteaism_ouma", "Milkteaism Ouma"),
        ("minato_aqua", "Minato Aqua"),
        ("mind_reader_himeko_v1_4", "Mind Reader himeko v1.4"),
        ("minimalist_lite", "Minimalist"),
        ("minimalist_2_0", "Minimalist 2.0"),
        ("mio_no_hanabi_no_yoru_koshii", "Mio no hanabi no yoru"),
        ("miraie_2_0", "Miraie 2.0 (Pink & White)"),
        ("mlaw_v1_0", "Mlaw v1.0 (Aesthetic 1.2)"),
        ("MonkoEdit", "MonkoEdit"),
        ("moonlight_classic", "Moonlight (Classic)"),
        ("mrekk_2_0_nm", "mrekk 2.0 NM"),
        ("mrekk_3_0_abyssal", "mrekk 3.0 (Abyssal ver.)"),
        ("mugio3_2015", "mugio3"),
        ("muki_ar11_boop2_blue", "muki ar11 boop 2.0 blue"),
        ("mumei_classic", "Mumei"),
        ("musim_dingin_a7", "Musim Dingin 'A7"),
        ("komori_noel_v5", "N O E L V 5 (Komori)"),
        ("nakano_itsuki", "Nakano Itsuki"),
        ("decadence_lite", "Nakiri Ayame - DECADENCE"),
        ("naru_v3_0", "Naru V3.0"),
        ("navers_blues_skin", "Naver's blue's skin"),
        ("nayssu", "Nayssu"),
        ("neastroelb_komori_sevil", "NeastroelB - Komori (SevIl)"),
        ("necrotrash_skin", "necrotrash's skin"),
        ("neko", "Neko"),
        ("nekoha_shizuku", "Nekoha Shizuku"),
        ("nekomata_okayu_gken", "Nekomata Okayu"),
        ("neynda_remaster", "Neynda. Remaster"),
        ("night_fall", "night faLL"),
        ("ninodurian_v1_nt", "NinoDurian v1.0"),
        ("ninomae_ina_nis_blooxoo_gameplay", "Ninomae Ina'nis (BlooXoo gameplay)"),
        ("nixen_skinmesh", "Nixen_ skinmesh"),
        ("no_se", "no+se"),
        ("nochito_chocomint_nt_1_2", "Nochito Chocomint 1.2"),
        ("noel_chan", "Noel Chan"),
        ("noshiro_a33_red_ver", "Noshiro (Azur Lane) Red ver."),
        ("notmiku", "notMiku"),
        ("oozora_subaru", "Oozora Subaru"),
        ("oozora_subaru_ratchet", "Oozora Subaru (2)"),
        ("osu_default_skin_improved", "osu! Default skin improved"),
        ("osu_retro", "osu!Retro"),
        ("osu_shot_dual_color", "osu!shot dual-color"),
        ("ouro_kronii_nm", "Ouro Kronii (NM)"),
        ("overdrive", "Overdrive"),
        ("owc_skin_remake", "owc Skin Remake"),
        ("owoTunaCK1.4Mathi", "owoTuna (CK 1.4 Mathi ver.)"),
        ("owoTunaCK1.4", "owoTuna (CK 1.4)"),
        ("owotuna_ryan_blue", "owotuna ryan blue"),
        ("owotuna_1_4_bjlly", "owoTuna v1.4 (bjlly)"),
        ("owotuna_1_4_selyu_shige", "owoTuna v1.4 Selyu Shige"),
        ("pareless_v1", "Pareless v1"),
        ("patchouli_knowledge", "Patchouli Knowledge"),
        ("pegulian_komori", "Pegulian (Komori)"),
        ("pegulian_ii_komori", "Pegulian II (Komori)"),
        ("pink_n_aqua_aquasimp_remake_nm", "Pink'n'Aqua aquasimp remake (NM)"),
        ("planetsJesusOmega", "Planets (JesusOmega NM)"),
        ("ppengy_chroma_edit_instafade", "ppengy chroma edit instafade"),
        ("prang_gb", "Prang"),
        ("prawilosc_vjp_without_followpoints", "Prawilosc vJP without followpoints"),
        ("pretty_cool_and_good", "pretty cool and good"),
        ("prism_v3", "Prism v3"),
        ("prjct_x", "prjct. X"),
        ("project_irys_lite", "Project IRyS"),
        ("project_kaheru", "Project Kaheru"),
        ("project_lucia", "Project L U C I A"),
        ("project_mashiro", "Project MASHIRO"),
        ("project_shirakami", "Project Shirakami"),
        ("project_voez_optimized_v2_4", "Project VOEZ v2.4"),
        ("project_voez_v3_1", "Project VOEZ v3.1"),
        ("purple_mathi", "Purple Mathi"),
        ("purplestar_sk_nonweeb_fix", "PurpleStar (Non-weeb)"),
        ("qiqi_genshin_impact_n7", "Qiqi Genshin Impact"),
        ("quasicrystal", "QuasiCrystal"),
        ("RafisHDDT2018-03-26", "Rafis HDDT 2018-03-26"),
        ("rafisHDDT2021rk", "Rafis HDDT 2020 ft [R/K]"),
        ("rafisNecrofantasia2.0rk", "Rafis Necrofantasia [RK] Main"),
        ("raidoken_ck_0_9", "Raidoken 0.9"),
        ("raiko_watanabe_patatau_hddt", "Raiko Watanabe (Patatau HDDT)"),
        ("randoline", "Randoline"),
        ("raniemi_2018_05_11", "Raniemi (2018-05-11)"),
        ("re-abstract", "re;abstract"),
        ("re_owotuna_v1_1_ck", "re;owotuna v1.1 CK"),
        ("re_owotuna_v1_1_mk", "re;owotuna v1.1 MK"),
        ("re_owotuna_v1_1_selyu", "re;owotuna v1.1 Selyu"),
        ("re_pannomimi", "re;Pannomimi"),
        ("red_pixel_2018_10_27", "Red Pixel 2018-10-27"),
        ("reesespuffs_skin_v1", "ReesesPuffs v1"),
        ("reflection", "Reflection"),
        ("rem-altalia", "Rem (AT)"),
        ("rem_nk_nonweeb", "Rem (Non-weeb)"),
        ("remilia_scarlet", "Remilia Scarlet"),
        ("remilia_scarlet_khz", "Remilia Scarlet (khz)"),
        ("remrin_", "Remrin~"),
        ("rohulk_4_0", "Rohulk 4.0"),
        ("roxy_migurdia_ak", "Roxy Migurdia"),
        ("rrtyui", "rrtyui"),
        ("Rustbell-2018-04-01", "Rustbell (2018-04-01)"),
        ("dpeaces_rustbell_edit", "rustbell edit"),
        ("rwby_rose_alquin_edit", "RWBY Rose Alquin Edit"),
        ("ryan_mystia_thing", "ryan mystia thing"),
        ("ryanstolefromkevin", "ryanstolefromkevin"),
        ("ryuk_monko", "RyuK Monko"),
        ("saber_alter", "Saber Alter"),
        ("saberstrike_0", "SaberStrike 0"),
        ("sbr_ah_holo", "SaberStrike ah HOLO"),
        ("saberstrike_v1", "SaberStrike v1"),
        ("saberstrike_v1_1_dt", "SaberStrike v1.1 DT"),
        ("sakamata_chloe_nyuh", "Sakamata Chloe"),
        ("sakamata_chloe_nm_by", "Sakamata Chloe NM"),
        ("satou_matsuzaka_x_shio", "Satou Matsuzaka x Shio"),
        ("scarlet_devil_himeko_v1_1", "Scarlet Devil Himeko v1.1"),
        ("selyu_v2_3", "Selyu v2.3"),
        ("senko_san_hideru", "Senko san Hideru"),
        ("seoul_v10", "Seoul v10"),
        ("seoul_v9_pineapple_color", "Seoul v9 Pineapple Color (shige)"),
        ("shield", "Shield"),
        ("shigera_elaina", "Shigera Elaina"),
        ("shige03_2013_kamui", "Shigetora 03 (2013 - Kamui)"),
        ("shige17", "Shigetora 17 (2016-02-27)"),
        ("shige18", "Shigetora 18 (Seouless v5)"),
        ("shige21.4", "Shigetora 21.4 (2017-02-24)"),
        ("shige25", "Shigetora 25 (2017-10-16)"),
        ("shige29", "Shigetora 29"),
        ("shige33", "Shigetora 33 (2018-09-02)"),
        ("shige35", "Shigetora 35 (2018-10-27)"),
        ("mashiro", "Shiina Mashiro"),
        ("shiki_ryougi", "Shiki Ryougi"),
        ("oshino_v2_0", "Shinobu Oshino v2.0"),
        ("shion_yorigami", "Shion Yorigami"),
        ("denyings_shirogane_noel", "Shirogane Noel"),
        ("shishiro_botan", "Shishiro Botan"),
        ("simplify_1_1", "Simplify 1.1"),
        ("simpline", "Simpline"),
        ("skin_not_found_404_defreeyay_ver", "Skin not Found 404 (defreeyay ver.)"),
        ("sokrates_v1_0_lite_fix", "Sokrates v1.0"),
        ("solo_leveling_ak", "Solo Leveling [AK]"),
        ("soyvinn_v2_red", "SoyVinn v2 RED"),
        ("space_amber", "Space Amber"),
        ("span_lite", "Span"),
        ("spazza17_skin_recreation", "Spazza17 Skin Recreation"),
        ("spowoky2020", "Spowoky 2020"),
        ("sputnix_nm_v1_1", "Sputnix v1.1 (NM)"),
        ("sriracha_rice_fy", "Sriracha Rice (FY)"),
        ("starry_sky", "Starry Sky"),
        ("stellar_into_the_galaxy", "Stellar into the Galaxy"),
        ("sugoi_v5", "Sugoi v5"),
        ("SuicideCat-skin", "Suicide Cat skin"),
        ("sunaookami_shiroko_swimsuit", "Sunaookami Shiroko (swimsuit)"),
        ("taiga_aisaka_ak", "Taiga Aisaka [AK]"),
        ("takanashi_hoshino_swimsuit", "Takanashi Hoshino (swimsuit)"),
        ("technov3_potla", "TechnoV3 (Potla)"),
        ("tekkito", "tekkito"),
        ("tekkito_remake_koi_edit", "Tekkito Remake Koi Edit"),
        ("texas_v1_0", "Texas v1.0"),
        ("the_journey_of_elaina_v1_1", "The Journey of Elaina v1.1"),
        ("the_memory_of_mumei_lite_sigma", "The Memory of Mumei"),
        ("the_rocket_league_skin", "The Rocket League Skin"),
        ("the_simple_skin", "The simple skin"),
        ("thekushvanman_skin_10_11_21", "TheKushVanMan (2021-11-10)"),
        ("thelewa_2017_08_10", "thelewa (2017-08-10)"),
        ("thepoon", "ThePooN"),
        ("tippy_karcher_remake", "Tippy (Karcher Remake)"),
        ("to_r", "TO-R"),
        ("toaru_railgun_sz", "Toaru Railgun"),
        ("tohsaka_sz", "Tohsaka Rin"),
        ("tokio", "Tokio"),
        ("tokizuki", "Tokizuki"),
        ("tokoyami_towa_ms", "Tokoyami Towa"),
        ("tony_varv", "tony varv"),
        ("touhou_khz_v1_2", "Touhou v1.2 [khz]"),
        ("towamajitenshi_v1_01", "Toyokami Towa v1.01"),
        ("tranquil_sublimity", "Tranquil Sublimity"),
        ("tsunomaki_watame", "Tsunomaki Watame"),
        ("tunayugen_oka", "TunaYugen"),
        ("twice_hirai_momo", "TWICE Hirai Momo"),
        ("twixiepink_v2_mix_nm", "TwixiePink v2 Mix (NM)"),
        ("undercurrents", "undercurrents"),
        ("unnamed_weeb_skin", "unnamed weeb skin"),
        ("drink33_s_uruha_rushia_v2", "Uruha Rushia V2"),
        ("usc_2020", "USC 2020"),
        ("varvalian_delis", "Varvalian (Delis w/o bamboo sounds)"),
        ("baconBoiCK1.0_blue", "Vaxei (CK Bacon boi 1.0 blue)"),
        ("baconBoiCK1.0", "Vaxei (CK Bacon boi 1.0)"),
        ("vaxei_2018_12_09", "Vaxei 2018-12-09"),
        ("vaxei_hashtag", "Vaxei#"),
        ("vladaadv3", "vladaad's skin v3"),
        ("vopbe_skin_v2_0", "Vopbe Skin v2.0"),
        ("walnut_1_0_clrs_ht", "Walnut 1.0 clrs"),
        ("wedzy_white_red_record_v1", "Wedzy White-Red v1"),
        ("whitecatCK1.0", "WhiteCat (CK 1.0)"),
        ("whitecatCK2.0", "WhiteCat (CK 2.0)"),
        ("whitecat_2_1_dt_ck_rk", "WhiteCat 2.1 DT (CK/RK)"),
        ("whitecat_2_1_ez_ck_rk", "WhiteCat 2.1 EZ (CK/RK)"),
        ("whitecat_2_1_old_ck", "WhiteCat 2.1 old (CK)"),
        ("wiek2.2", "Wiek 2.2"),
        ("wiek2_2_new", "Wiek 2.2 new"),
        ("willy", "Willy"),
        ("wintermachi_2_1", "WINTERMASHI 2.1"),
        ("wintherest", "Wintherest"),
        ("wubwoofwolf_1.8_stalehuman_dt", "WubWoofWolf 1.8 (Stale Human DT edit)"),
        ("wubwoofwolf2.01", "WubWoofWolf 2.01"),
        ("www_v1_2_2014_01_08", "WubWoofWolf v1.2 (2014-01-08)"),
        ("xd_mau5", "xd mau5"),
        ("xenoblade_2_lite", "Xenoblade 2"),
        ("xilver", "Xilver"),
        ("xilver_x_recia", "Xilver x Recia"),
        ("xilver15_2020_08_27", "Xilver15 2020-08-27"),
        ("xingchen_stardust_sn", "Xingchen Stardust"),
        ("xoomoon_frankie_edit", "XooMoon Frankie Edit"),
        ("yab_wb", "YaB WB"),
        ("yamls_nm", "YAMLS (NM)"),
        ("yellow_biscuits_lite", "Yellow Biscuits 1.0"),
        ("yon", "Yon"),
        ("yons_colors_various_artists", "Yons Colors"),
        ("YoRHa", "YoRHa"),
        ("YUGEN", "YUGEN"),
        ("yumeko_jabami", "Yumeko Jabami"),
        ("zei_v5", "Zei v5"),
        ("zelda101_skin", "zelda101's skin"),
        ("zirba_2017_08_10", "Zirba 2017-08-10"),
        ("zofainsley_revamped", "Zofainsley Revampled"),
        ("zylice_oka", "Zylice"),
    ])
});
