[bot]
client_id = "client_id"
guild_id = "guild_id"
token = "token"
public_key = "public_key"

[database]
mongodb_uri = "mongodb_uri"

[api]
saucenao_key = "saucenao_key"
spotify_token = "spotify_token"
steam_key = "steam_key"
virtualearth_key = "virtualearth_key"