pub static CONTROL_CHARACTERS: [[&str; 2]; 32] = [
    ["0", "NULL"],
    ["1", "START OF HEADING"],
    ["2", "START OF TEXT"],
    ["3", "END OF TEXT"],
    ["4", "END OF TRANSMISSION"],
    ["5", "ENQUIRY"],
    ["6", "ACKNOWLEDGE"],
    ["7", "BELL"],
    ["8", "BACKSPACE"],
    ["9", "CHARACTER TABULATION"],
    ["A", "LINE FEED (LF)"],
    ["B", "LINE TABULATION"],
    ["C", "FORM FEED (FF)"],
    ["D", "CARRIAGE RETURN (CR)"],
    ["E", "SHIFT OUT"],
    ["F", "SHIFT IN"],
    ["10", "DATA LINK ESCAPE"],
    ["11", "DEVICE CONTROL ONE"],
    ["12", "DEVICE CONTROL TWO"],
    ["13", "DEVICE CONTROL THREE"],
    ["14", "DEVICE CONTROL FOUR"],
    ["15", "NEGATIVE ACKNOWLEDGE"],
    ["16", "SYNCHRONOUS IDLE"],
    ["17", "END OF TRANSMISSION BLOCK"],
    ["18", "CANCEL"],
    ["19", "END OF MEDIUM"],
    ["1A", "SUBSTITUTE"],
    ["1B", "ESCAPE"],
    ["1C", "INFORMATION SEPARATOR FOUR"],
    ["1D", "INFORMATION SEPARATOR THREE"],
    ["1E", "INFORMATION SEPARATOR TWO"],
    ["1F", "INFORMATION SEPARATOR ONE"],
];
