use crate::macros::group;

group! {
    calculate,
    convert_currency,
    code,
    define,
    google,
    google_translate_context,
    heliohost,
    inspect_message,
    ip,
    osu,
    owner,
    reminder,
    reminder_set_context,
    sauce,
    shorten_url,
    snipe,
    snipe_reaction_context,
    tag,
    timeout,
    unicode,
    user,
    voice_message,
    voice_message_context,
}
