use crate::structs::api::piston::PistonRuntime;
use std::sync::LazyLock;

pub static PISTON_RUNTIMES: LazyLock<Vec<PistonRuntime>> = LazyLock::new(|| {
    // runtimes.map(runtime => `PistonRuntime::new("${runtime.language}", "${runtime.version}", &${JSON.stringify(runtime.aliases)}, ${runtime.runtime ? `Some("${runtime.runtime}")` : "None"})`).join(", ");
    vec![
        PistonRuntime::new("matl", "22.5.0", &[], None),
        PistonRuntime::new("matl", "22.7.4", &[], None),
        PistonRuntime::new("bash", "5.2.0", &["sh"], None),
        PistonRuntime::new("befunge93", "0.2.0", &["b93"], None),
        PistonRuntime::new("bqn", "1.0.0", &[], None),
        PistonRuntime::new("brachylog", "1.0.0", &[], None),
        PistonRuntime::new("brainfuck", "2.7.3", &["bf"], None),
        PistonRuntime::new("cjam", "0.6.5", &[], None),
        PistonRuntime::new("clojure", "1.10.3", &["clojure", "clj"], None),
        PistonRuntime::new("cobol", "3.1.2", &["cob"], None),
        PistonRuntime::new("coffeescript", "2.5.1", &["coffeescript", "coffee"], None),
        PistonRuntime::new("cow", "1.0.0", &["cow"], None),
        PistonRuntime::new("crystal", "0.36.1", &["crystal", "cr"], None),
        PistonRuntime::new("dart", "2.19.6", &[], None),
        PistonRuntime::new("dash", "0.5.11", &["dash"], None),
        PistonRuntime::new("typescript", "1.32.3", &["deno", "deno-ts"], Some("deno")),
        PistonRuntime::new("javascript", "1.32.3", &["deno-js"], Some("deno")),
        PistonRuntime::new(
            "basic.net",
            "5.0.201",
            &["basic", "visual-basic", "visual-basic.net", "vb", "vb.net", "vb-dotnet", "dotnet-vb", "basic-dotnet", "dotnet-basic"],
            Some("dotnet"),
        ),
        PistonRuntime::new(
            "fsharp.net",
            "5.0.201",
            &[
                "fsharp",
                "fs",
                "f#",
                "fs.net",
                "f#.net",
                "fsharp-dotnet",
                "fs-dotnet",
                "f#-dotnet",
                "dotnet-fsharp",
                "dotnet-fs",
                "dotnet-fs",
            ],
            Some("dotnet"),
        ),
        PistonRuntime::new(
            "csharp.net",
            "5.0.201",
            &[
                "csharp",
                "c#",
                "cs",
                "c#.net",
                "cs.net",
                "c#-dotnet",
                "cs-dotnet",
                "csharp-dotnet",
                "dotnet-c#",
                "dotnet-cs",
                "dotnet-csharp",
            ],
            Some("dotnet"),
        ),
        PistonRuntime::new(
            "fsi",
            "5.0.201",
            &["fsx", "fsharp-interactive", "f#-interactive", "dotnet-fsi", "fsi-dotnet", "fsi.net"],
            Some("dotnet"),
        ),
        PistonRuntime::new("dragon", "1.9.8", &[], None),
        PistonRuntime::new("elixir", "1.11.3", &["elixir", "exs"], None),
        PistonRuntime::new("emacs", "27.1.0", &["emacs", "el", "elisp"], None),
        PistonRuntime::new("emojicode", "1.0.2", &["emojic"], None),
        PistonRuntime::new("erlang", "23.0.0", &["erlang", "erl", "escript"], None),
        PistonRuntime::new("file", "0.0.1", &["executable", "elf", "binary"], None),
        PistonRuntime::new("forte", "1.0.0", &["forter"], None),
        PistonRuntime::new("forth", "0.7.3", &["gforth"], None),
        PistonRuntime::new("freebasic", "1.9.0", &["bas", "fbc", "basic", "qbasic", "quickbasic"], None),
        PistonRuntime::new("awk", "5.1.0", &["gawk"], Some("gawk")),
        PistonRuntime::new("c", "10.2.0", &["gcc"], Some("gcc")),
        PistonRuntime::new("c++", "10.2.0", &["cpp", "g++"], Some("gcc")),
        PistonRuntime::new("d", "10.2.0", &["gdc"], Some("gcc")),
        PistonRuntime::new("fortran", "10.2.0", &["fortran", "f90"], Some("gcc")),
        PistonRuntime::new("go", "1.16.2", &["go", "golang"], None),
        PistonRuntime::new("golfscript", "1.0.0", &["golfscript"], None),
        PistonRuntime::new("groovy", "3.0.7", &["groovy", "gvy"], None),
        PistonRuntime::new("haskell", "9.0.1", &["haskell", "hs"], None),
        PistonRuntime::new("husk", "1.0.0", &[], None),
        PistonRuntime::new("iverilog", "11.0.0", &["verilog", "vvp"], None),
        PistonRuntime::new("japt", "2.0.0", &["japt"], None),
        PistonRuntime::new("java", "15.0.2", &[], None),
        PistonRuntime::new("jelly", "0.1.31", &[], None),
        PistonRuntime::new("julia", "1.8.5", &["jl"], None),
        PistonRuntime::new("kotlin", "1.8.20", &["kt"], None),
        PistonRuntime::new("lisp", "2.1.2", &["lisp", "cl", "sbcl", "commonlisp"], None),
        PistonRuntime::new("llvm_ir", "12.0.1", &["llvm", "llvm-ir", "ll"], None),
        PistonRuntime::new("lolcode", "0.11.2", &["lol", "lci"], None),
        PistonRuntime::new("lua", "5.4.4", &[], None),
        PistonRuntime::new("csharp", "6.12.0", &["mono", "mono-csharp", "mono-c#", "mono-cs", "c#", "cs"], Some("mono")),
        PistonRuntime::new("basic", "6.12.0", &["vb", "mono-vb", "mono-basic", "visual-basic", "visual basic"], Some("mono")),
        PistonRuntime::new("nasm", "2.15.5", &["asm", "nasm32"], Some("nasm")),
        PistonRuntime::new("nasm64", "2.15.5", &["asm64"], Some("nasm")),
        PistonRuntime::new("nim", "1.6.2", &[], None),
        PistonRuntime::new("javascript", "18.15.0", &["node-javascript", "node-js", "javascript", "js"], Some("node")),
        PistonRuntime::new("ocaml", "4.12.0", &["ocaml", "ml"], None),
        PistonRuntime::new("octave", "8.1.0", &["matlab", "m"], None),
        PistonRuntime::new("osabie", "1.0.1", &["osabie", "05AB1E", "usable"], None),
        PistonRuntime::new("paradoc", "0.6.0", &["paradoc"], None),
        PistonRuntime::new("pascal", "3.2.2", &["freepascal", "pp", "pas"], None),
        PistonRuntime::new("perl", "5.36.0", &["pl"], None),
        PistonRuntime::new("php", "8.2.3", &[], None),
        PistonRuntime::new("ponylang", "0.39.0", &["pony", "ponyc"], None),
        PistonRuntime::new("prolog", "8.2.4", &["prolog", "plg"], None),
        PistonRuntime::new("pure", "0.68.0", &[], None),
        PistonRuntime::new("powershell", "7.1.4", &["ps", "pwsh", "ps1"], Some("pwsh")),
        PistonRuntime::new("pyth", "1.0.0", &["pyth"], None),
        PistonRuntime::new("python2", "2.7.18", &["py2", "python2"], None),
        PistonRuntime::new("python", "3.10.0", &["py", "py3", "python3", "python3.10"], None),
        PistonRuntime::new("racket", "8.3.0", &["rkt"], None),
        PistonRuntime::new("raku", "6.100.0", &["raku", "rakudo", "perl6", "p6", "pl6"], None),
        PistonRuntime::new("retina", "1.2.0", &["ret"], None),
        PistonRuntime::new("rockstar", "1.0.0", &["rock", "rocky"], None),
        PistonRuntime::new("rscript", "4.1.1", &["r"], None),
        PistonRuntime::new("ruby", "3.0.1", &["ruby3", "rb"], None),
        PistonRuntime::new("rust", "1.68.2", &["rs"], None),
        PistonRuntime::new("samarium", "0.3.1", &["sm"], None),
        PistonRuntime::new("scala", "3.2.2", &["sc"], None),
        PistonRuntime::new("smalltalk", "3.2.3", &["st"], None),
        PistonRuntime::new("sqlite3", "3.36.0", &["sqlite", "sql"], None),
        PistonRuntime::new("swift", "5.3.3", &["swift"], None),
        PistonRuntime::new("typescript", "5.0.3", &["ts", "node-ts", "tsc", "typescript5", "ts5"], None),
        PistonRuntime::new("vlang", "0.3.3", &["v"], None),
        PistonRuntime::new("vyxal", "2.4.1", &[], None),
        PistonRuntime::new("yeethon", "3.10.0", &["yeethon3"], None),
        PistonRuntime::new("zig", "0.10.1", &[], None),
    ]
});
