use crate::structs::api::piston::PistonRuntime;
use std::{collections::HashMap, sync::LazyLock};

pub static PISTON_RUNTIMES: LazyLock<HashMap<String, PistonRuntime>> = LazyLock::new(|| {
    // runtimes.map(runtime => `("${runtime.runtime ?? runtime.language}".into(), PistonRuntime::new("${runtime.language}", "${runtime.version}", &${JSON.stringify(runtime.aliases)}, ${runtime.runtime ? `Some("${runtime.runtime}")` : "None"}))`).join(", ");
    HashMap::from([
        ("matl".into(), PistonRuntime::new("matl", "22.5.0", &[], None)),
        ("matl".into(), PistonRuntime::new("matl", "22.7.4", &[], None)),
        ("bash".into(), PistonRuntime::new("bash", "5.2.0", &["sh"], None)),
        ("befunge93".into(), PistonRuntime::new("befunge93", "0.2.0", &["b93"], None)),
        ("bqn".into(), PistonRuntime::new("bqn", "1.0.0", &[], None)),
        ("brachylog".into(), PistonRuntime::new("brachylog", "1.0.0", &[], None)),
        ("brainfuck".into(), PistonRuntime::new("brainfuck", "2.7.3", &["bf"], None)),
        ("cjam".into(), PistonRuntime::new("cjam", "0.6.5", &[], None)),
        ("clojure".into(), PistonRuntime::new("clojure", "1.10.3", &["clojure", "clj"], None)),
        ("cobol".into(), PistonRuntime::new("cobol", "3.1.2", &["cob"], None)),
        ("coffeescript".into(), PistonRuntime::new("coffeescript", "2.5.1", &["coffeescript", "coffee"], None)),
        ("cow".into(), PistonRuntime::new("cow", "1.0.0", &["cow"], None)),
        ("crystal".into(), PistonRuntime::new("crystal", "0.36.1", &["crystal", "cr"], None)),
        ("dart".into(), PistonRuntime::new("dart", "2.19.6", &[], None)),
        ("dash".into(), PistonRuntime::new("dash", "0.5.11", &["dash"], None)),
        ("deno".into(), PistonRuntime::new("typescript", "1.32.3", &["deno", "deno-ts"], Some("deno"))),
        ("deno".into(), PistonRuntime::new("javascript", "1.32.3", &["deno-js"], Some("deno"))),
        (
            "dotnet".into(),
            PistonRuntime::new(
                "basic.net",
                "5.0.201",
                &["basic", "visual-basic", "visual-basic.net", "vb", "vb.net", "vb-dotnet", "dotnet-vb", "basic-dotnet", "dotnet-basic"],
                Some("dotnet"),
            ),
        ),
        (
            "dotnet".into(),
            PistonRuntime::new(
                "fsharp.net",
                "5.0.201",
                &[
                    "fsharp",
                    "fs",
                    "f#",
                    "fs.net",
                    "f#.net",
                    "fsharp-dotnet",
                    "fs-dotnet",
                    "f#-dotnet",
                    "dotnet-fsharp",
                    "dotnet-fs",
                    "dotnet-fs",
                ],
                Some("dotnet"),
            ),
        ),
        (
            "dotnet".into(),
            PistonRuntime::new(
                "csharp.net",
                "5.0.201",
                &[
                    "csharp",
                    "c#",
                    "cs",
                    "c#.net",
                    "cs.net",
                    "c#-dotnet",
                    "cs-dotnet",
                    "csharp-dotnet",
                    "dotnet-c#",
                    "dotnet-cs",
                    "dotnet-csharp",
                ],
                Some("dotnet"),
            ),
        ),
        (
            "dotnet".into(),
            PistonRuntime::new(
                "fsi",
                "5.0.201",
                &["fsx", "fsharp-interactive", "f#-interactive", "dotnet-fsi", "fsi-dotnet", "fsi.net"],
                Some("dotnet"),
            ),
        ),
        ("dragon".into(), PistonRuntime::new("dragon", "1.9.8", &[], None)),
        ("elixir".into(), PistonRuntime::new("elixir", "1.11.3", &["elixir", "exs"], None)),
        ("emacs".into(), PistonRuntime::new("emacs", "27.1.0", &["emacs", "el", "elisp"], None)),
        ("emojicode".into(), PistonRuntime::new("emojicode", "1.0.2", &["emojic"], None)),
        ("erlang".into(), PistonRuntime::new("erlang", "23.0.0", &["erlang", "erl", "escript"], None)),
        ("file".into(), PistonRuntime::new("file", "0.0.1", &["executable", "elf", "binary"], None)),
        ("forte".into(), PistonRuntime::new("forte", "1.0.0", &["forter"], None)),
        ("forth".into(), PistonRuntime::new("forth", "0.7.3", &["gforth"], None)),
        ("freebasic".into(), PistonRuntime::new("freebasic", "1.9.0", &["bas", "fbc", "basic", "qbasic", "quickbasic"], None)),
        ("gawk".into(), PistonRuntime::new("awk", "5.1.0", &["gawk"], Some("gawk"))),
        ("gcc".into(), PistonRuntime::new("c", "10.2.0", &["gcc"], Some("gcc"))),
        ("gcc".into(), PistonRuntime::new("c++", "10.2.0", &["cpp", "g++"], Some("gcc"))),
        ("gcc".into(), PistonRuntime::new("d", "10.2.0", &["gdc"], Some("gcc"))),
        ("gcc".into(), PistonRuntime::new("fortran", "10.2.0", &["fortran", "f90"], Some("gcc"))),
        ("go".into(), PistonRuntime::new("go", "1.16.2", &["go", "golang"], None)),
        ("golfscript".into(), PistonRuntime::new("golfscript", "1.0.0", &["golfscript"], None)),
        ("groovy".into(), PistonRuntime::new("groovy", "3.0.7", &["groovy", "gvy"], None)),
        ("haskell".into(), PistonRuntime::new("haskell", "9.0.1", &["haskell", "hs"], None)),
        ("husk".into(), PistonRuntime::new("husk", "1.0.0", &[], None)),
        ("iverilog".into(), PistonRuntime::new("iverilog", "11.0.0", &["verilog", "vvp"], None)),
        ("japt".into(), PistonRuntime::new("japt", "2.0.0", &["japt"], None)),
        ("java".into(), PistonRuntime::new("java", "15.0.2", &[], None)),
        ("jelly".into(), PistonRuntime::new("jelly", "0.1.31", &[], None)),
        ("julia".into(), PistonRuntime::new("julia", "1.8.5", &["jl"], None)),
        ("kotlin".into(), PistonRuntime::new("kotlin", "1.8.20", &["kt"], None)),
        ("lisp".into(), PistonRuntime::new("lisp", "2.1.2", &["lisp", "cl", "sbcl", "commonlisp"], None)),
        ("llvm_ir".into(), PistonRuntime::new("llvm_ir", "12.0.1", &["llvm", "llvm-ir", "ll"], None)),
        ("lolcode".into(), PistonRuntime::new("lolcode", "0.11.2", &["lol", "lci"], None)),
        ("lua".into(), PistonRuntime::new("lua", "5.4.4", &[], None)),
        ("mono".into(), PistonRuntime::new("csharp", "6.12.0", &["mono", "mono-csharp", "mono-c#", "mono-cs", "c#", "cs"], Some("mono"))),
        (
            "mono".into(),
            PistonRuntime::new("basic", "6.12.0", &["vb", "mono-vb", "mono-basic", "visual-basic", "visual basic"], Some("mono")),
        ),
        ("nasm".into(), PistonRuntime::new("nasm", "2.15.5", &["asm", "nasm32"], Some("nasm"))),
        ("nasm".into(), PistonRuntime::new("nasm64", "2.15.5", &["asm64"], Some("nasm"))),
        ("nim".into(), PistonRuntime::new("nim", "1.6.2", &[], None)),
        ("node".into(), PistonRuntime::new("javascript", "18.15.0", &["node-javascript", "node-js", "javascript", "js"], Some("node"))),
        ("ocaml".into(), PistonRuntime::new("ocaml", "4.12.0", &["ocaml", "ml"], None)),
        ("octave".into(), PistonRuntime::new("octave", "8.1.0", &["matlab", "m"], None)),
        ("osabie".into(), PistonRuntime::new("osabie", "1.0.1", &["osabie", "05AB1E", "usable"], None)),
        ("paradoc".into(), PistonRuntime::new("paradoc", "0.6.0", &["paradoc"], None)),
        ("pascal".into(), PistonRuntime::new("pascal", "3.2.2", &["freepascal", "pp", "pas"], None)),
        ("perl".into(), PistonRuntime::new("perl", "5.36.0", &["pl"], None)),
        ("php".into(), PistonRuntime::new("php", "8.2.3", &[], None)),
        ("ponylang".into(), PistonRuntime::new("ponylang", "0.39.0", &["pony", "ponyc"], None)),
        ("prolog".into(), PistonRuntime::new("prolog", "8.2.4", &["prolog", "plg"], None)),
        ("pure".into(), PistonRuntime::new("pure", "0.68.0", &[], None)),
        ("pwsh".into(), PistonRuntime::new("powershell", "7.1.4", &["ps", "pwsh", "ps1"], Some("pwsh"))),
        ("pyth".into(), PistonRuntime::new("pyth", "1.0.0", &["pyth"], None)),
        ("python2".into(), PistonRuntime::new("python2", "2.7.18", &["py2", "python2"], None)),
        ("python".into(), PistonRuntime::new("python", "3.10.0", &["py", "py3", "python3", "python3.10"], None)),
        ("racket".into(), PistonRuntime::new("racket", "8.3.0", &["rkt"], None)),
        ("raku".into(), PistonRuntime::new("raku", "6.100.0", &["raku", "rakudo", "perl6", "p6", "pl6"], None)),
        ("retina".into(), PistonRuntime::new("retina", "1.2.0", &["ret"], None)),
        ("rockstar".into(), PistonRuntime::new("rockstar", "1.0.0", &["rock", "rocky"], None)),
        ("rscript".into(), PistonRuntime::new("rscript", "4.1.1", &["r"], None)),
        ("ruby".into(), PistonRuntime::new("ruby", "3.0.1", &["ruby3", "rb"], None)),
        ("rust".into(), PistonRuntime::new("rust", "1.68.2", &["rs"], None)),
        ("samarium".into(), PistonRuntime::new("samarium", "0.3.1", &["sm"], None)),
        ("scala".into(), PistonRuntime::new("scala", "3.2.2", &["sc"], None)),
        ("smalltalk".into(), PistonRuntime::new("smalltalk", "3.2.3", &["st"], None)),
        ("sqlite3".into(), PistonRuntime::new("sqlite3", "3.36.0", &["sqlite", "sql"], None)),
        ("swift".into(), PistonRuntime::new("swift", "5.3.3", &["swift"], None)),
        ("typescript".into(), PistonRuntime::new("typescript", "5.0.3", &["ts", "node-ts", "tsc", "typescript5", "ts5"], None)),
        ("vlang".into(), PistonRuntime::new("vlang", "0.3.3", &["v"], None)),
        ("vyxal".into(), PistonRuntime::new("vyxal", "2.4.1", &[], None)),
        ("yeethon".into(), PistonRuntime::new("yeethon", "3.10.0", &["yeethon3"], None)),
        ("zig".into(), PistonRuntime::new("zig", "0.10.1", &[], None)),
    ])
});
