use std::{collections::HashMap, sync::LazyLock};

// [...document.querySelector("select").options].map(x => [x.attributes[0].value, x.label])

pub static DISTRIBUTIONS: LazyLock<HashMap<&str, &str>> = LazyLock::new(|| {
    HashMap::from([
        ("3cx", "3CX"),
        ("4mlinux", "4MLinux"),
        ("absolute", "Absolute"),
        ("ac", "Accessible-Coconut"),
        ("alma", "AlmaLinux"),
        ("alpine", "Alpine"),
        ("alt", "ALT"),
        ("antix", "antiX"),
        ("arch", "Arch"),
        ("archbang", "ArchBang"),
        ("archcraft", "Archcraft"),
        ("archman", "Archman"),
        ("arco", "ArcoLinux"),
        ("armbian", "Armbian"),
        ("artix", "Artix"),
        ("athena", "Athena"),
        ("austrumi", "AUSTRUMI"),
        ("", "AV Linux"),
        ("backbox", "BackBox"),
        ("baruwa", "Baruwa"),
        ("batocera", "Batocera"),
        ("bedrock", "Bedrock"),
        ("berry", "Berry"),
        ("bicom", "Bicom"),
        ("biglinux", "BigLinux"),
        ("blackarch", "BlackArch"),
        ("blendos", "blendOS"),
        ("blueonyx", "BlueOnyx"),
        ("bluestar", "Bluestar"),
        ("bodhi", "Bodhi"),
        ("bros", "Br OS"),
        ("bsdrp", "BSDRP"),
        ("bunsenlabs", "BunsenLabs"),
        ("cachyos", "CachyOS"),
        ("caine", "CAINE"),
        ("calculate", "Calculate"),
        ("canaima", "Canaima"),
        ("centos", "CentOS"),
        ("clear", "Clear"),
        ("clonezilla", "Clonezilla"),
        ("commodore", "Commodore"),
        ("crowz", "CROWZ"),
        ("cbpp", "Crunchbangplusplus"),
        ("crux", "CRUX"),
        ("damnsmall", "Damn Small"),
        ("daphile", "Daphile"),
        ("debian", "Debian"),
        ("skolelinux", "Debian Edu"),
        ("deepin", "deepin"),
        ("devuan", "Devuan"),
        ("diamond", "Diamond"),
        ("dietpi", "DietPi"),
        ("drparted", "Dr.Parted"),
        ("dragonflybsd", "DragonFly"),
        ("dragora", "Dragora"),
        ("dynebolic", "Dynebolic"),
        ("dynfi", "DynFi"),
        ("easynas", "EasyNAS"),
        ("easyos", "EasyOS"),
        ("edubuntu", "Edubuntu"),
        ("elearnix", "eLearnix"),
        ("elementary", "elementary"),
        ("elive", "Elive"),
        ("emmabuntus", "Emmabuntüs"),
        ("endeavour", "EndeavourOS"),
        ("endian", "Endian"),
        ("endless", "Endless"),
        ("eurolinux", "EuroLinux"),
        ("exe", "Exe"),
        ("exherbo", "Exherbo"),
        ("extix", "ExTiX"),
        ("fatdog", "Fatdog64"),
        ("fedora", "Fedora"),
        ("ferenos", "Feren"),
        ("finnix", "Finnix"),
        ("freebsd", "FreeBSD"),
        ("freedombox", "FreedomBox"),
        ("freepbx", "FreePBX"),
        ("freespire", "Freespire"),
        ("fuguita", "FuguIta"),
        ("funtoo", "Funtoo"),
        ("garuda", "Garuda"),
        ("gecko", "Gecko"),
        ("gentoo", "Gentoo"),
        ("ghostbsd", "GhostBSD"),
        ("gnoppix", "Gnoppix"),
        ("gparted", "GParted"),
        ("grml", "Grml"),
        ("guixsd", "Guix System"),
        ("haiku", "Haiku"),
        ("hamonikr", "HamoniKR"),
        ("hardenedbsd", "HardenedBSD"),
        ("hellosystem", "hellosystem"),
        ("hyperbola", "Hyperbola"),
        ("ipfire", "IPFire"),
        ("kaisen", "Kaisen"),
        ("kali", "Kali"),
        ("kanotix", "KANOTIX"),
        ("kaos", "KaOS"),
        ("karoshi", "Karoshi"),
        ("kdeneon", "KDE neon"),
        ("kodachi", "Kodachi"),
        ("kolibri", "KolibriOS"),
        ("kubuntu", "Kubuntu"),
        ("kumander", "Kumander"),
        ("kwort", "Kwort"),
        ("lakka", "Lakka"),
        ("legacy", "Legacy"),
        ("lernstick", "Lernstick"),
        ("lfs", "LFS"),
        ("libreelec", "LibreELEC"),
        ("linspire", "Linspire"),
        ("linuxfx", "Linuxfx"),
        ("lite", "Lite"),
        ("liveraizo", "Live Raizo"),
        ("liya", "Liya"),
        ("lliurex", "LliureX"),
        ("lubuntu", "Lubuntu"),
        ("lxle", "LXLE"),
        ("mabox", "Mabox"),
        ("mageia", "Mageia"),
        ("maid", "mAid"),
        ("makulu", "MakuluLinux"),
        ("manjaro", "Manjaro"),
        ("max", "MAX"),
        ("midnightbsd", "MidnightBSD"),
        ("mint", "Mint"),
        ("miracle", "MIRACLE"),
        ("murena", "Murena"),
        ("mx", "MX Linux"),
        ("navy", "Navy"),
        ("neptune", "Neptune"),
        ("netbsd", "NetBSD"),
        ("nethsecurity", "NethSecurity"),
        ("netrunner", "Netrunner"),
        ("nexentastor", "NexentaStor"),
        ("nitrux", "Nitrux"),
        ("nixos", "NixOS"),
        ("nobara", "Nobara"),
        ("nomadbsd", "NomadBSD"),
        ("nova", "Nova"),
        ("nst", "NST"),
        ("nutyx", "NuTyX"),
        ("ob2d", "OB2D"),
        ("obarun", "Obarun"),
        ("omoikane", "Omoikane"),
        ("openbsd", "OpenBSD"),
        ("openindiana", "OpenIndiana"),
        ("openmamba", "openmamba"),
        ("openmandriva", "OpenMandriva"),
        ("openmediavault", "OpenMediaVault"),
        ("opensuse", "openSUSE"),
        ("opnsense", "OPNsense"),
        ("oracle", "Oracle"),
        ("osgeo", "OSGeoLive"),
        ("osmc", "OSMC"),
        ("ovios", "OviOS"),
        ("pakos", "PakOS"),
        ("paldo", "paldo"),
        ("parabola", "Parabola"),
        ("pardus", "Pardus"),
        ("parrot", "Parrot"),
        ("partedmagic", "Parted Magic"),
        ("pclinuxos", "PCLinuxOS"),
        ("pearl", "Pearl"),
        ("pentoo", "Pentoo"),
        ("peppermint", "Peppermint"),
        ("peropesis", "Peropesis"),
        ("pfsense", "pfSense"),
        ("photonos", "Photon"),
        ("pisi", "Pisi"),
        ("plamo", "Plamo"),
        ("pld", "PLD"),
        ("plop", "Plop"),
        ("popos", "Pop!_OS"),
        ("porteus", "Porteus"),
        ("porteuskiosk", "Porteus Kiosk"),
        ("postmarketos", "postmarketOS"),
        ("primtux", "PrimTux"),
        ("proxmox", "Proxmox"),
        ("puppy", "Puppy"),
        ("pureos", "PureOS"),
        ("q4os", "Q4OS"),
        ("qubes", "Qubes"),
        ("raspios", "RasPiOS"),
        ("rds", "RDS"),
        ("reactos", "ReactOS"),
        ("rebeccablackos", "RebeccaBlackOS"),
        ("rebornos", "RebornOS"),
        ("recalbox", "Recalbox"),
        ("redhat", "Red Hat"),
        ("redcore", "Redcore"),
        ("refracta", "Refracta"),
        ("regata", "Regata"),
        ("relianoid", "RELIANOID"),
        ("rescuezilla", "Rescuezilla"),
        ("rhino", "Rhino"),
        ("risc", "RISC"),
        ("risios", "risiOS"),
        ("rlxos", "rlxos"),
        ("robolinux", "Robolinux"),
        ("rockstor", "Rockstor"),
        ("rocky", "Rocky"),
        ("rosa", "ROSA"),
        ("rss", "RSS"),
        ("runtu", "Runtu"),
        ("salix", "Salix"),
        ("sdesk", "SDesk"),
        ("selks", "SELKS"),
        ("siduction", "siduction"),
        ("skudonet", "Skudonet"),
        ("slackel", "Slackel"),
        ("slackware", "Slackware"),
        ("slax", "Slax"),
        ("slint", "Slint"),
        ("slitaz", "SliTaz"),
        ("smartos", "SmartOS"),
        ("smeserver", "SME Server"),
        ("snal", "Snal"),
        ("solaris", "Solaris"),
        ("solus", "Solus"),
        ("solydxk", "SolydXK"),
        ("sparky", "SparkyLinux"),
        ("spiral", "SpiralLinux"),
        ("springdale", "Springdale"),
        ("supergrub", "Super Grub2"),
        ("sle", "SUSE"),
        ("syslinuxos", "SysLinuxOS"),
        ("systemrescue", "SystemRescue"),
        ("t2", "T2"),
        ("tails", "Tails"),
        ("thinstation", "Thinstation"),
        ("tinycore", "Tiny Core"),
        ("trisquel", "Trisquel"),
        ("truenas", "TrueNAS"),
        ("turnkey", "TurnKey"),
        ("tuxedo", "TUXEDO"),
        ("ubos", "UBOS"),
        ("ubports", "UBports"),
        ("ubuntu", "Ubuntu"),
        ("ubuntubudgie", "Ubuntu Budgie"),
        ("ubuntuce", "Ubuntu Christian"),
        ("ubuntucinnamon", "Ubuntu Cinnamon"),
        ("ubuntukylin", "Ubuntu Kylin"),
        ("ubuntumate", "Ubuntu MATE"),
        ("ubuntudp", "Ubuntu Pack"),
        ("ubuntustudio", "Ubuntu Studio"),
        ("ubuntuunity", "Ubuntu Unity"),
        ("ufficiozero", "Ufficio Zero"),
        ("ultimate", "Ultimate"),
        ("ultramarine", "Ultramarine"),
        ("univention", "Univention"),
        ("untangle", "Untangle"),
        ("uruk", "Uruk"),
        ("vanilla", "Vanilla"),
        ("venom", "Venom"),
        ("vine", "Vine"),
        ("void", "Void"),
        ("volumio", "Volumio"),
        ("voyager", "Voyager"),
        ("vyos", "VyOS"),
        ("wattos", "wattOS"),
        ("whonix", "Whonix"),
        ("wifislax", "Wifislax"),
        ("wmlive", "WM Live"),
        ("xigmanas", "XigmaNAS"),
        ("xubuntu", "Xubuntu"),
        ("yunohost", "YunoHost"),
        ("zentyal", "Zentyal"),
        ("zenwalk", "Zenwalk"),
        ("zephix", "Zephix"),
        ("zorin", "Zorin"),
    ])
});
