pub const CURRENCIES: [[&str; 2]; 171] = [
    ["United Arab Emirates Dirham", "AED"],
    ["Afghan Afghani", "AFN"],
    ["Albanian Lek", "ALL"],
    ["Armenian Dram", "AMD"],
    ["Netherlands Antillean Guilder", "ANG"],
    ["Angolan Kwanza", "AOA"],
    ["Argentine Peso", "ARS"],
    ["Australian Dollar", "AUD"],
    ["Aruban Florin", "AWG"],
    ["Azerbaijani Manat", "AZN"],
    ["Bosnia-Herzegovina Convertible Mark", "BAM"],
    ["Barbadian Dollar", "BBD"],
    ["Bangladeshi Taka", "BDT"],
    ["Bulgarian Lev", "BGN"],
    ["Bahraini Dinar", "BHD"],
    ["Burundian Franc", "BIF"],
    ["Bermudan Dollar", "BMD"],
    ["Brunei Dollar", "BND"],
    ["Bolivian Boliviano", "BOB"],
    ["Brazilian Real", "BRL"],
    ["Bahamian Dollar", "BSD"],
    ["Bitcoin", "BTC"],
    ["Bhutanese Ngultrum", "BTN"],
    ["Botswanan Pula", "BWP"],
    ["Belarusian Ruble", "BYN"],
    ["Belize Dollar", "BZD"],
    ["Canadian Dollar", "CAD"],
    ["Congolese Franc", "CDF"],
    ["Swiss Franc", "CHF"],
    ["Chilean Unit of Account (UF)", "CLF"],
    ["Chilean Peso", "CLP"],
    ["Chinese Yuan (Offshore)", "CNH"],
    ["Chinese Yuan", "CNY"],
    ["Colombian Peso", "COP"],
    ["Costa Rican Colón", "CRC"],
    ["Cuban Convertible Peso", "CUC"],
    ["Cuban Peso", "CUP"],
    ["Cape Verdean Escudo", "CVE"],
    ["Czech Republic Koruna", "CZK"],
    ["Djiboutian Franc", "DJF"],
    ["Danish Krone", "DKK"],
    ["Dominican Peso", "DOP"],
    ["Algerian Dinar", "DZD"],
    ["Egyptian Pound", "EGP"],
    ["Eritrean Nakfa", "ERN"],
    ["Ethiopian Birr", "ETB"],
    ["Euro", "EUR"],
    ["Fijian Dollar", "FJD"],
    ["Falkland Islands Pound", "FKP"],
    ["British Pound Sterling", "GBP"],
    ["Georgian Lari", "GEL"],
    ["Guernsey Pound", "GGP"],
    ["Ghanaian Cedi", "GHS"],
    ["Gibraltar Pound", "GIP"],
    ["Gambian Dalasi", "GMD"],
    ["Guinean Franc", "GNF"],
    ["Guatemalan Quetzal", "GTQ"],
    ["Guyanaese Dollar", "GYD"],
    ["Hong Kong Dollar", "HKD"],
    ["Honduran Lempira", "HNL"],
    ["Croatian Kuna", "HRK"],
    ["Haitian Gourde", "HTG"],
    ["Hungarian Forint", "HUF"],
    ["Indonesian Rupiah", "IDR"],
    ["Israeli New Sheqel", "ILS"],
    ["Manx pound", "IMP"],
    ["Indian Rupee", "INR"],
    ["Iraqi Dinar", "IQD"],
    ["Iranian Rial", "IRR"],
    ["Icelandic Króna", "ISK"],
    ["Jersey Pound", "JEP"],
    ["Jamaican Dollar", "JMD"],
    ["Jordanian Dinar", "JOD"],
    ["Japanese Yen", "JPY"],
    ["Kenyan Shilling", "KES"],
    ["Kyrgystani Som", "KGS"],
    ["Cambodian Riel", "KHR"],
    ["Comorian Franc", "KMF"],
    ["North Korean Won", "KPW"],
    ["South Korean Won", "KRW"],
    ["Kuwaiti Dinar", "KWD"],
    ["Cayman Islands Dollar", "KYD"],
    ["Kazakhstani Tenge", "KZT"],
    ["Laotian Kip", "LAK"],
    ["Lebanese Pound", "LBP"],
    ["Sri Lankan Rupee", "LKR"],
    ["Liberian Dollar", "LRD"],
    ["Lesotho Loti", "LSL"],
    ["Libyan Dinar", "LYD"],
    ["Moroccan Dirham", "MAD"],
    ["Moldovan Leu", "MDL"],
    ["Malagasy Ariary", "MGA"],
    ["Macedonian Denar", "MKD"],
    ["Myanma Kyat", "MMK"],
    ["Mongolian Tugrik", "MNT"],
    ["Macanese Pataca", "MOP"],
    ["Mauritanian Ouguiya (pre-2018)", "MRO"],
    ["Mauritanian Ouguiya", "MRU"],
    ["Mauritian Rupee", "MUR"],
    ["Maldivian Rufiyaa", "MVR"],
    ["Malawian Kwacha", "MWK"],
    ["Mexican Peso", "MXN"],
    ["Malaysian Ringgit", "MYR"],
    ["Mozambican Metical", "MZN"],
    ["Namibian Dollar", "NAD"],
    ["Nigerian Naira", "NGN"],
    ["Nicaraguan Córdoba", "NIO"],
    ["Norwegian Krone", "NOK"],
    ["Nepalese Rupee", "NPR"],
    ["New Zealand Dollar", "NZD"],
    ["Omani Rial", "OMR"],
    ["Panamanian Balboa", "PAB"],
    ["Peruvian Nuevo Sol", "PEN"],
    ["Papua New Guinean Kina", "PGK"],
    ["Philippine Peso", "PHP"],
    ["Pakistani Rupee", "PKR"],
    ["Polish Zloty", "PLN"],
    ["Paraguayan Guarani", "PYG"],
    ["Qatari Rial", "QAR"],
    ["Romanian Leu", "RON"],
    ["Serbian Dinar", "RSD"],
    ["Russian Ruble", "RUB"],
    ["Rwandan Franc", "RWF"],
    ["Saudi Riyal", "SAR"],
    ["Solomon Islands Dollar", "SBD"],
    ["Seychellois Rupee", "SCR"],
    ["Sudanese Pound", "SDG"],
    ["Swedish Krona", "SEK"],
    ["Singapore Dollar", "SGD"],
    ["Saint Helena Pound", "SHP"],
    ["Sierra Leonean Leone", "SLL"],
    ["Somali Shilling", "SOS"],
    ["Surinamese Dollar", "SRD"],
    ["South Sudanese Pound", "SSP"],
    ["São Tomé and Príncipe Dobra (pre-2018)", "STD"],
    ["São Tomé and Príncipe Dobra", "STN"],
    ["Salvadoran Colón", "SVC"],
    ["Syrian Pound", "SYP"],
    ["Swazi Lilangeni", "SZL"],
    ["Thai Baht", "THB"],
    ["Tajikistani Somoni", "TJS"],
    ["Turkmenistani Manat", "TMT"],
    ["Tunisian Dinar", "TND"],
    ["Tongan Pa'anga", "TOP"],
    ["Turkish Lira", "TRY"],
    ["Trinidad and Tobago Dollar", "TTD"],
    ["New Taiwan Dollar", "TWD"],
    ["Tanzanian Shilling", "TZS"],
    ["Ukrainian Hryvnia", "UAH"],
    ["Ugandan Shilling", "UGX"],
    ["United States Dollar", "USD"],
    ["Uruguayan Peso", "UYU"],
    ["Uzbekistan Som", "UZS"],
    ["Venezuelan Bolívar Fuerte (Old)", "VEF"],
    ["Venezuelan Bolívar Soberano", "VES"],
    ["Vietnamese Dong", "VND"],
    ["Vanuatu Vatu", "VUV"],
    ["Samoan Tala", "WST"],
    ["CFA Franc BEAC", "XAF"],
    ["Silver Ounce", "XAG"],
    ["Gold Ounce", "XAU"],
    ["East Caribbean Dollar", "XCD"],
    ["Special Drawing Rights", "XDR"],
    ["CFA Franc BCEAO", "XOF"],
    ["Palladium Ounce", "XPD"],
    ["CFP Franc", "XPF"],
    ["Platinum Ounce", "XPT"],
    ["Yemeni Rial", "YER"],
    ["South African Rand", "ZAR"],
    ["Zambian Kwacha", "ZMW"],
    ["Zimbabwean Dollar", "ZWL"],
];

pub const CONTROL_CHARACTERS: [[&str; 2]; 32] = [
    ["0", "NULL"],
    ["1", "START OF HEADING"],
    ["2", "START OF TEXT"],
    ["3", "END OF TEXT"],
    ["4", "END OF TRANSMISSION"],
    ["5", "ENQUIRY"],
    ["6", "ACKNOWLEDGE"],
    ["7", "BELL"],
    ["8", "BACKSPACE"],
    ["9", "CHARACTER TABULATION"],
    ["A", "LINE FEED (LF)"],
    ["B", "LINE TABULATION"],
    ["C", "FORM FEED (FF)"],
    ["D", "CARRIAGE RETURN (CR)"],
    ["E", "SHIFT OUT"],
    ["F", "SHIFT IN"],
    ["10", "DATA LINK ESCAPE"],
    ["11", "DEVICE CONTROL ONE"],
    ["12", "DEVICE CONTROL TWO"],
    ["13", "DEVICE CONTROL THREE"],
    ["14", "DEVICE CONTROL FOUR"],
    ["15", "NEGATIVE ACKNOWLEDGE"],
    ["16", "SYNCHRONOUS IDLE"],
    ["17", "END OF TRANSMISSION BLOCK"],
    ["18", "CANCEL"],
    ["19", "END OF MEDIUM"],
    ["1A", "SUBSTITUTE"],
    ["1B", "ESCAPE"],
    ["1C", "INFORMATION SEPARATOR FOUR"],
    ["1D", "INFORMATION SEPARATOR THREE"],
    ["1E", "INFORMATION SEPARATOR TWO"],
    ["1F", "INFORMATION SEPARATOR ONE"],
];

pub const GOOGLE_TRANSLATE_LANGUAGES: [[&str; 2]; 105] = [
    ["auto", "Automatic"],
    ["af", "Afrikaans"],
    ["sq", "Albanian"],
    ["am", "Amharic"],
    ["ar", "Arabic"],
    ["hy", "Armenian"],
    ["az", "Azerbaijani"],
    ["eu", "Basque"],
    ["be", "Belarusian"],
    ["bn", "Bengali"],
    ["bs", "Bosnian"],
    ["bg", "Bulgarian"],
    ["ca", "Catalan"],
    ["ceb", "Cebuano"],
    ["ny", "Chichewa"],
    ["zh-CN", "Chinese Simplified"],
    ["zh-TW", "Chinese Traditional"],
    ["co", "Corsican"],
    ["hr", "Croatian"],
    ["cs", "Czech"],
    ["da", "Danish"],
    ["nl", "Dutch"],
    ["en", "English"],
    ["eo", "Esperanto"],
    ["et", "Estonian"],
    ["tl", "Filipino"],
    ["fi", "Finnish"],
    ["fr", "French"],
    ["fy", "Frisian"],
    ["gl", "Galician"],
    ["ka", "Georgian"],
    ["de", "German"],
    ["el", "Greek"],
    ["gu", "Gujarati"],
    ["ht", "Haitian Creole"],
    ["ha", "Hausa"],
    ["haw", "Hawaiian"],
    ["iw", "Hebrew"],
    ["hi", "Hindi"],
    ["hmn", "Hmong"],
    ["hu", "Hungarian"],
    ["is", "Icelandic"],
    ["ig", "Igbo"],
    ["id", "Indonesian"],
    ["ga", "Irish"],
    ["it", "Italian"],
    ["ja", "Japanese"],
    ["jw", "Javanese"],
    ["kn", "Kannada"],
    ["kk", "Kazakh"],
    ["km", "Khmer"],
    ["ko", "Korean"],
    ["ku", "Kurdish (Kurmanji)"],
    ["ky", "Kyrgyz"],
    ["lo", "Lao"],
    ["la", "Latin"],
    ["lv", "Latvian"],
    ["lt", "Lithuanian"],
    ["lb", "Luxembourgish"],
    ["mk", "Macedonian"],
    ["mg", "Malagasy"],
    ["ms", "Malay"],
    ["ml", "Malayalam"],
    ["mt", "Maltese"],
    ["mi", "Maori"],
    ["mr", "Marathi"],
    ["mn", "Mongolian"],
    ["my", "Myanmar (Burmese)"],
    ["ne", "Nepali"],
    ["no", "Norwegian"],
    ["ps", "Pashto"],
    ["fa", "Persian"],
    ["pl", "Polish"],
    ["pt", "Portuguese"],
    ["ma", "Punjabi"],
    ["ro", "Romanian"],
    ["ru", "Russian"],
    ["sm", "Samoan"],
    ["gd", "Scots Gaelic"],
    ["sr", "Serbian"],
    ["st", "Sesotho"],
    ["sn", "Shona"],
    ["sd", "Sindhi"],
    ["si", "Sinhala"],
    ["sk", "Slovak"],
    ["sl", "Slovenian"],
    ["so", "Somali"],
    ["es", "Spanish"],
    ["su", "Sundanese"],
    ["sw", "Swahili"],
    ["sv", "Swedish"],
    ["tg", "Tajik"],
    ["ta", "Tamil"],
    ["te", "Telugu"],
    ["th", "Thai"],
    ["tr", "Turkish"],
    ["uk", "Ukrainian"],
    ["ur", "Urdu"],
    ["uz", "Uzbek"],
    ["vi", "Vietnamese"],
    ["cy", "Welsh"],
    ["xh", "Xhosa"],
    ["yi", "Yiddish"],
    ["yo", "Yoruba"],
    ["zu", "Zulu"],
];

pub const DNS_CODES: [[&str; 2]; 10] = [
    ["NOERROR", "DNS Query completed successfully."],
    ["FORMERR", "DNS Query Format Error."],
    ["SERVFAIL", "Server failed to complete the DNS request."],
    ["NXDOMAIN", "Domain name does not exist."],
    ["NOTIMP", "Function not implemented."],
    ["REFUSED", "The server refused to answer for the query."],
    ["YXDOMAIN", "Name that should not exist, does exist."],
    ["XRRSET", "RRset that should not exist, does exist."],
    ["NOTAUTH", "Server not authoritative for the zone."],
    ["NOTZONE", "Name not in zone."],
];
