use std::sync::LazyLock;
use std::collections::HashMap;

pub static XE_CURRENCIES: LazyLock<HashMap<&str, &str>> = LazyLock::new(|| {
    HashMap::from([
        ("GBP", "British Pound"),
        ("USD", "US Dollar"),
        ("EUR", "Euro"),
        ("CAD", "Canadian Dollar"),
        ("AUD", "Australian Dollar"),
        ("JPY", "Japanese Yen"),
        ("INR", "Indian Rupee"),
        ("NZD", "New Zealand Dollar"),
        ("CHF", "Swiss Franc"),
        ("ZAR", "South African Rand"),
        ("RUB", "Russian Ruble"),
        ("BGN", "Bulgarian Lev"),
        ("SGD", "Singapore Dollar"),
        ("HKD", "Hong Kong Dollar"),
        ("SEK", "Swedish Krona"),
        ("THB", "Thai Baht"),
        ("HUF", "Hungarian Forint"),
        ("CNY", "Chinese Yuan"),
        ("NOK", "Norwegian Krone"),
        ("MXN", "Mexican Peso"),
        ("DKK", "Danish Krone"),
        ("MYR", "Malaysian Ringgit"),
        ("PLN", "Polish Zloty"),
        ("BRL", "Brazilian Real"),
        ("PHP", "Philippine Peso"),
        ("IDR", "Indonesian Rupiah"),
        ("CZK", "Czech Koruna"),
        ("AED", "United Arab Emirates Dirham"),
        ("TWD", "New Taiwan Dollar"),
        ("KRW", "South Korean Won"),
        ("ILS", "Israeli New Shekel"),
        ("ARS", "Argentine Peso"),
        ("CLP", "Chilean Peso"),
        ("EGP", "Egyptian Pound"),
        ("TRY", "Turkish Lira"),
        ("RON", "Romanian Leu"),
        ("SAR", "Saudi Riyal"),
        ("PKR", "Pakistani Rupee"),
        ("COP", "Colombian Peso"),
        ("IQD", "Iraqi Dinar"),
        ("XAU", "Gold Ounce"),
        ("FJD", "Fijian Dollar"),
        ("KWD", "Kuwaiti Dinar"),
        ("BAM", "Bosnia-Herzegovina Convertible Mark"),
        ("ISK", "Icelandic Króna"),
        ("MAD", "Moroccan Dirham"),
        ("HRK", "Croatian Kuna"),
        ("VND", "Vietnamese Dong"),
        ("JMD", "Jamaican Dollar"),
        ("JOD", "Jordanian Dinar"),
        ("DOP", "Dominican Peso"),
        ("PEN", "Peruvian Sol"),
        ("CRC", "Costa Rican Colón"),
        ("BHD", "Bahraini Dinar"),
        ("BDT", "Bangladeshi Taka"),
        ("DZD", "Algerian Dinar"),
        ("KES", "Kenyan Shilling"),
        ("XAG", "Silver Ounce"),
        ("LKR", "Sri Lankan Rupee"),
        ("OMR", "Omani Rial"),
        ("QAR", "Qatari Riyal"),
        ("IRR", "Iranian Rial"),
        ("TND", "Tunisian Dinar"),
        ("TTD", "Trinidad & Tobago Dollar"),
        ("ZMW", "Zambian Kwacha"),
        ("BBD", "Barbadian Dollar"),
        ("NGN", "Nigerian Naira"),
        ("LBP", "Lebanese Pound"),
        ("MUR", "Mauritian Rupee"),
        ("XPT", "Platinum Ounce"),
        ("BSD", "Bahamian Dollar"),
        ("ALL", "Albanian Lek"),
        ("UYU", "Uruguayan Peso"),
        ("BMD", "Bermudan Dollar"),
        ("LVL", "Latvian Lat"),
        ("UAH", "Ukrainian Hryvnia"),
        ("GTQ", "Guatemalan Quetzal"),
        ("BWP", "Botswanan Pula"),
        ("BOB", "Bolivian Boliviano"),
        ("CUP", "Cuban Peso"),
        ("PYG", "Paraguayan Guarani"),
        ("HNL", "Honduran Lempira"),
        ("LTL", "Lithuanian Litas"),
        ("ZWD", "Zimbabwean Dollar"),
        ("NIO", "Nicaraguan Córdoba"),
        ("RSD", "Serbian Dinar"),
        ("NPR", "Nepalese Rupee"),
        ("HTG", "Haitian Gourde"),
        ("PAB", "Panamanian Balboa"),
        ("SVC", "Salvadoran Colón"),
        ("GYD", "Guyanaese Dollar"),
        ("KYD", "Cayman Islands Dollar"),
        ("TZS", "Tanzanian Shilling"),
        ("CVE", "Cape Verdean Escudo"),
        ("FKP", "Falkland Islands Pound"),
        ("ANG", "Netherlands Antillean Guilder"),
        ("UGX", "Ugandan Shilling"),
        ("MGA", "Malagasy Ariary"),
        ("GEL", "Georgian Lari"),
        ("ETB", "Ethiopian Birr"),
        ("MDL", "Moldovan Leu"),
        ("VUV", "Vanuatu Vatu"),
        ("SYP", "Syrian Pound"),
        ("BND", "Brunei Dollar"),
        ("KHR", "Cambodian Riel"),
        ("NAD", "Namibian Dollar"),
        ("MKD", "Macedonian Denar"),
        ("AOA", "Angolan Kwanza"),
        ("PGK", "Papua New Guinean Kina"),
        ("MMK", "Myanmar Kyat"),
        ("KZT", "Kazakhstani Tenge"),
        ("MOP", "Macanese Pataca"),
        ("MZN", "Mozambican Metical"),
        ("LYD", "Libyan Dinar"),
        ("SLL", "Sierra Leonean Leone (1964—2022)"),
        ("GNF", "Guinean Franc"),
        ("BYR", "Belarusian Ruble"),
        ("GMD", "Gambian Dalasi"),
        ("AWG", "Aruban Florin"),
        ("AMD", "Armenian Dram"),
        ("YER", "Yemeni Rial"),
        ("LAK", "Laotian Kip"),
        ("WST", "Samoan Tala"),
        ("MWK", "Malawian Kwacha"),
        ("KPW", "North Korean Won"),
        ("BIF", "Burundian Franc"),
        ("DJF", "Djiboutian Franc"),
        ("MNT", "Mongolian Tugrik"),
        ("UZS", "Uzbekistani Som"),
        ("TOP", "Tongan Paʻanga"),
        ("SCR", "Seychellois Rupee"),
        ("KGS", "Kyrgystani Som"),
        ("BTN", "Bhutanese Ngultrum"),
        ("SBD", "Solomon Islands Dollar"),
        ("GIP", "Gibraltar Pound"),
        ("RWF", "Rwandan Franc"),
        ("CDF", "Congolese Franc"),
        ("MVR", "Maldivian Rufiyaa"),
        ("ERN", "Eritrean Nakfa"),
        ("SOS", "Somali Shilling"),
        ("SZL", "Swazi Lilangeni"),
        ("TJS", "Tajikistani Somoni"),
        ("LRD", "Liberian Dollar"),
        ("LSL", "Lesotho Loti"),
        ("SHP", "St. Helena Pound"),
        ("KMF", "Comorian Franc"),
        ("SPL", "Seborgan Luigino"),
        ("TMT", "Turkmenistani Manat"),
        ("SRD", "Surinamese Dollar"),
        ("IMP", "Isle of Man Pound"),
        ("JEP", "Jersey Pound"),
        ("TVD", "Tuvaluan Dollar"),
        ("GGP", "Guernsey Pound"),
        ("AFN", "Afghan Afghani"),
        ("AZN", "Azerbaijani Manat"),
        ("BZD", "Belize Dollar"),
        ("CUC", "Cuban Convertible Peso"),
        ("GHS", "Ghanaian Cedi"),
        ("SDG", "Sudanese Pound"),
        ("VEF", "Venezuelan Bolivar"),
        ("XPD", "Palladium Ounce"),
        ("MRO", "Mauritanian Ouguiya"),
        ("STD", "Sao Tomean Dobra"),
        ("VEB", "Venezuelan Bolivar"),
        ("XBT", "Bitcoin"),
        ("MYR", "Malaysian Ringgit"),
        ("USD", "US Dollar"),
        ("EUR", "Euro"),
        ("GBP", "British Pound"),
        ("CAD", "Canadian Dollar"),
        ("AUD", "Australian Dollar"),
        ("JPY", "Japanese Yen"),
        ("INR", "Indian Rupee"),
        ("NZD", "New Zealand Dollar"),
        ("CHF", "Swiss Franc"),
        ("ZAR", "South African Rand"),
        ("RUB", "Russian Ruble"),
        ("BGN", "Bulgarian Lev"),
        ("SGD", "Singapore Dollar"),
        ("HKD", "Hong Kong Dollar"),
        ("SEK", "Swedish Krona"),
        ("THB", "Thai Baht"),
        ("HUF", "Hungarian Forint"),
        ("CNY", "Chinese Yuan"),
        ("NOK", "Norwegian Krone"),
        ("MXN", "Mexican Peso"),
        ("DKK", "Danish Krone"),
        ("PLN", "Polish Zloty"),
        ("BRL", "Brazilian Real"),
        ("PHP", "Philippine Peso"),
        ("IDR", "Indonesian Rupiah"),
        ("CZK", "Czech Koruna"),
        ("AED", "United Arab Emirates Dirham"),
        ("TWD", "New Taiwan Dollar"),
        ("KRW", "South Korean Won"),
        ("ILS", "Israeli New Shekel"),
        ("ARS", "Argentine Peso"),
        ("CLP", "Chilean Peso"),
        ("EGP", "Egyptian Pound"),
        ("TRY", "Turkish Lira"),
        ("RON", "Romanian Leu"),
        ("SAR", "Saudi Riyal"),
        ("PKR", "Pakistani Rupee"),
        ("COP", "Colombian Peso"),
        ("IQD", "Iraqi Dinar"),
        ("XAU", "Gold Ounce"),
        ("FJD", "Fijian Dollar"),
        ("KWD", "Kuwaiti Dinar"),
        ("BAM", "Bosnia-Herzegovina Convertible Mark"),
        ("ISK", "Icelandic Króna"),
        ("MAD", "Moroccan Dirham"),
        ("HRK", "Croatian Kuna"),
        ("VND", "Vietnamese Dong"),
        ("JMD", "Jamaican Dollar"),
        ("JOD", "Jordanian Dinar"),
        ("DOP", "Dominican Peso"),
        ("PEN", "Peruvian Sol"),
        ("CRC", "Costa Rican Colón"),
        ("BHD", "Bahraini Dinar"),
        ("BDT", "Bangladeshi Taka"),
        ("DZD", "Algerian Dinar"),
        ("KES", "Kenyan Shilling"),
        ("XAG", "Silver Ounce"),
        ("LKR", "Sri Lankan Rupee"),
        ("OMR", "Omani Rial"),
        ("QAR", "Qatari Riyal"),
        ("IRR", "Iranian Rial"),
        ("TND", "Tunisian Dinar"),
        ("TTD", "Trinidad & Tobago Dollar"),
        ("ZMW", "Zambian Kwacha"),
        ("BBD", "Barbadian Dollar"),
        ("NGN", "Nigerian Naira"),
        ("LBP", "Lebanese Pound"),
        ("MUR", "Mauritian Rupee"),
        ("XPT", "Platinum Ounce"),
        ("BSD", "Bahamian Dollar"),
        ("ALL", "Albanian Lek"),
        ("UYU", "Uruguayan Peso"),
        ("BMD", "Bermudan Dollar"),
        ("LVL", "Latvian Lat"),
        ("UAH", "Ukrainian Hryvnia"),
        ("GTQ", "Guatemalan Quetzal"),
        ("BWP", "Botswanan Pula"),
        ("BOB", "Bolivian Boliviano"),
        ("CUP", "Cuban Peso"),
        ("PYG", "Paraguayan Guarani"),
        ("HNL", "Honduran Lempira"),
        ("LTL", "Lithuanian Litas"),
        ("ZWD", "Zimbabwean Dollar"),
        ("NIO", "Nicaraguan Córdoba"),
        ("RSD", "Serbian Dinar"),
        ("NPR", "Nepalese Rupee"),
        ("HTG", "Haitian Gourde"),
        ("PAB", "Panamanian Balboa"),
        ("SVC", "Salvadoran Colón"),
        ("GYD", "Guyanaese Dollar"),
        ("KYD", "Cayman Islands Dollar"),
        ("TZS", "Tanzanian Shilling"),
        ("CVE", "Cape Verdean Escudo"),
        ("FKP", "Falkland Islands Pound"),
        ("ANG", "Netherlands Antillean Guilder"),
        ("UGX", "Ugandan Shilling"),
        ("MGA", "Malagasy Ariary"),
        ("GEL", "Georgian Lari"),
        ("ETB", "Ethiopian Birr"),
        ("MDL", "Moldovan Leu"),
        ("VUV", "Vanuatu Vatu"),
        ("SYP", "Syrian Pound"),
        ("BND", "Brunei Dollar"),
        ("KHR", "Cambodian Riel"),
        ("NAD", "Namibian Dollar"),
        ("MKD", "Macedonian Denar"),
        ("AOA", "Angolan Kwanza"),
        ("PGK", "Papua New Guinean Kina"),
        ("MMK", "Myanmar Kyat"),
        ("KZT", "Kazakhstani Tenge"),
        ("MOP", "Macanese Pataca"),
        ("MZN", "Mozambican Metical"),
        ("LYD", "Libyan Dinar"),
        ("SLL", "Sierra Leonean Leone (1964—2022)"),
        ("GNF", "Guinean Franc"),
        ("BYR", "Belarusian Ruble"),
        ("GMD", "Gambian Dalasi"),
        ("AWG", "Aruban Florin"),
        ("AMD", "Armenian Dram"),
        ("YER", "Yemeni Rial"),
        ("LAK", "Laotian Kip"),
        ("WST", "Samoan Tala"),
        ("MWK", "Malawian Kwacha"),
        ("KPW", "North Korean Won"),
        ("BIF", "Burundian Franc"),
        ("DJF", "Djiboutian Franc"),
        ("MNT", "Mongolian Tugrik"),
        ("UZS", "Uzbekistani Som"),
        ("TOP", "Tongan Paʻanga"),
        ("SCR", "Seychellois Rupee"),
        ("KGS", "Kyrgystani Som"),
        ("BTN", "Bhutanese Ngultrum"),
        ("SBD", "Solomon Islands Dollar"),
        ("GIP", "Gibraltar Pound"),
        ("RWF", "Rwandan Franc"),
        ("CDF", "Congolese Franc"),
        ("MVR", "Maldivian Rufiyaa"),
        ("ERN", "Eritrean Nakfa"),
        ("SOS", "Somali Shilling"),
        ("SZL", "Swazi Lilangeni"),
        ("TJS", "Tajikistani Somoni"),
        ("LRD", "Liberian Dollar"),
        ("LSL", "Lesotho Loti"),
        ("SHP", "St. Helena Pound"),
        ("KMF", "Comorian Franc"),
        ("SPL", "Seborgan Luigino"),
        ("TMT", "Turkmenistani Manat"),
        ("SRD", "Surinamese Dollar"),
        ("IMP", "Isle of Man Pound"),
        ("JEP", "Jersey Pound"),
        ("TVD", "Tuvaluan Dollar"),
        ("GGP", "Guernsey Pound"),
        ("AFN", "Afghan Afghani"),
        ("AZN", "Azerbaijani Manat"),
        ("BZD", "Belize Dollar"),
        ("CUC", "Cuban Convertible Peso"),
        ("GHS", "Ghanaian Cedi"),
        ("SDG", "Sudanese Pound"),
        ("VEF", "Venezuelan Bolivar"),
        ("XPD", "Palladium Ounce"),
        ("MRO", "Mauritanian Ouguiya"),
        ("STD", "Sao Tomean Dobra"),
        ("VEB", "Venezuelan Bolivar"),
        ("XBT", "Bitcoin"),
    ])
});
